# Version
version: '3.1'

# Setup
services:
  # PHP
  php:
    depends_on:
      - db
    image: project-slim-learn
    restart: always
    ports:
      - 5000:80
    volumes:
    - ./development:/var/www/html

# PHPMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 5050:80
    environment:
      PMA_HOST: db

# MySQL
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - slimlearn_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: slimlearn
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

# Volumes
volumes:
  slimlearn_db:
  slimlearn_uploads: